<template>
  <v-form>
    <v-container>
      <v-row>
        <v-col
          cols="12"
          sm="6"
          md="3"
        >
          <v-text-field
            label="Regular"
          ></v-text-field>
        </v-col>

        <v-col
          cols="12"
          sm="6"
          md="3"
        >
          <v-text-field
            label="Regular"
            placeholder="Placeholder"
          ></v-text-field>
        </v-col>

        <v-col
          cols="12"
          sm="6"
          md="3"
        >
          <v-text-field
            label="Solo"
            solo
          ></v-text-field>
        </v-col>

        <v-col
          cols="12"
          sm="6"
          md="3"
        >
          <v-text-field
            label="Solo"
            placeholder="Placeholder"
            solo
          ></v-text-field>
        </v-col>

        <v-col
          cols="12"
          sm="6"
          md="3"
        >
          <v-text-field
            label="Filled"
            filled
          ></v-text-field>
        </v-col>

        <v-col
          cols="12"
          sm="6"
          md="3"
        >
          <v-text-field
            label="Filled"
            placeholder="Placeholder"
            filled
          ></v-text-field>
        </v-col>

        <v-col
          cols="12"
          sm="6"
          md="3"
        >
          <v-text-field
            label="Outlined"
            outlined
          ></v-text-field>
        </v-col>

        <v-col
          cols="12"
          sm="6"
          md="3"
        >
          <v-text-field
            placeholder="Placeholder"
            outlined
          ></v-text-field>
        </v-col>
      </v-row>
    </v-container>
    <v-card>
    <v-container fluid>
      <v-row
        align="center"
      >
        <v-col cols="12">
          <v-autocomplete
            v-model="values"
            :items="items"
            outlined
            dense
            chips
            small-chips
            label="Outlined"
            multiple
          ></v-autocomplete>
        </v-col>
        <v-col cols="12">
          <v-autocomplete
            v-model="values"
            :items="items"
            dense
            chips
            small-chips
            label="Solo"
            multiple
            solo
          ></v-autocomplete>
        </v-col>
        <v-col cols="12">
          <v-autocomplete
            v-model="value"
            :items="items"
            dense
            filled
            label="Filled"
          ></v-autocomplete>
        </v-col>
      </v-row>
    </v-container>
    <v-container>
      <v-autocomplete
            v-model="collateralAcceptance"
            :items="tokens"
            item-text="symbol"
            placeholder="Choose collateral accepted"
            item-value="symbol"
            outlined
            dense
            rounded
            dark
            chips
            deletable-chips
            :menu-props="{ auto: true }"
            multiple
          >
            <template slot="selection" slot-scope="data">
              <v-chip
                class="mb-1"
                color="rgba(255, 255, 255, 0.1)"
                v-bind="data.attrs"
                :input-value="data.selected"
                close
                @click="data.select"
                @click:close="remove(data.item)"
              >
                <img
                  class="select-img"
                  :src="$mapImageCurrency(data.item.symbol)"
                  alt
                >
                <span style="font-weight: 500;font-size: 14px; margin-right: 10px">{{ data.item.symbol }}</span>
                <!-- <v-icon color="#FFFFFF" class="pointer">mdi-window-close</v-icon> -->
              </v-chip>
            </template>
            <template slot="item" slot-scope="data">
              <v-list-item-content>
                <v-list-item-title style="display: flex;align-items: center">
                  <img
                    class="select-img"
                    :src="$mapImageCurrency(data.item.symbol)"
                    alt
                  >
                  {{ data.item.symbol }}
                </v-list-item-title>
              </v-list-item-content>
            </template>
          </v-autocomplete>
    </v-container>
  </v-card>
  </v-form>
</template>
<script>
  export default {
    data: () => ({
      items: ['foo', 'bar', 'fizz', 'buzz', 'foo1', 'bar1', 'fizz1', 'buzz1', 'foo2', 'bar2', 'fizz2', 'buzz2', 'foo3', 'bar3', 'fizz3', 'buzz3'],
      values: ['foo', 'bar'],
      value: null,
      tokens: [
      {
         "id":1,
         "isWhitelistCollateral":true,
         "isWhitelistSupply":true,
         "usdExchange":0.060468,
         "isAcceptedAsCollateral":null,
         "isAcceptedAsLoan":null,
         "isAcceptedRepayment":null,
         "symbol":"DFY",
         "address":"0x20f1dE452e9057fe863b99d33CF82DBeE0C45B14"
      },
      {
         "id":2,
         "isWhitelistCollateral":true,
         "isWhitelistSupply":false,
         "usdExchange":33240,
         "isAcceptedAsCollateral":null,
         "isAcceptedAsLoan":null,
         "isAcceptedRepayment":null,
         "symbol":"BTC",
         "address":"0x52D2848E79861492795a2635B76493999F1EdB1F"
      },
      {
         "id":3,
         "isWhitelistCollateral":true,
         "isWhitelistSupply":false,
         "usdExchange":2035.73,
         "isAcceptedAsCollateral":null,
         "isAcceptedAsLoan":null,
         "isAcceptedRepayment":null,
         "symbol":"ETH",
         "address":"0xf827916F754297d7fF595e77c8dF8287fDE74BA4"
      },
      {
         "id":5,
         "isWhitelistCollateral":false,
         "isWhitelistSupply":true,
         "usdExchange":1.0,
         "isAcceptedAsCollateral":null,
         "isAcceptedAsLoan":null,
         "isAcceptedRepayment":null,
         "symbol":"USDT",
         "address":"0x362F62b601E80221abb8013c496055fbD297b0B5"
      },
      {
         "id":6,
         "isWhitelistCollateral":true,
         "isWhitelistSupply":false,
         "usdExchange":0.632972,
         "isAcceptedAsCollateral":null,
         "isAcceptedAsLoan":null,
         "isAcceptedRepayment":null,
         "symbol":"XRP",
         "address":"0x653b5410E4a15062cdEF91f9CEe930ca9B1832C4"
      },
      {
         "id":7,
         "isWhitelistCollateral":true,
         "isWhitelistSupply":false,
         "usdExchange":133.83,
         "isAcceptedAsCollateral":null,
         "isAcceptedAsLoan":null,
         "isAcceptedRepayment":null,
         "symbol":"LTC",
         "address":"0x395998D21d4Dd230f38247F84145Bd4d9afAaCa2"
      },
      {
         "id":8,
         "isWhitelistCollateral":false,
         "isWhitelistSupply":false,
         "usdExchange":48.03,
         "isAcceptedAsCollateral":null,
         "isAcceptedAsLoan":null,
         "isAcceptedRepayment":null,
         "symbol":"ETC",
         "address":"0x3d6545b08693daE087E957cb1180ee38B9e3c25E"
      },
      {
         "id":9,
         "isWhitelistCollateral":false,
         "isWhitelistSupply":false,
         "usdExchange":107.95,
         "isAcceptedAsCollateral":null,
         "isAcceptedAsLoan":null,
         "isAcceptedRepayment":null,
         "symbol":"ZEC",
         "address":"0x1Ba42e5193dfA8B03D15dd1B86a3113bbBEF8Eeb"
      },
      {
         "id":10,
         "isWhitelistCollateral":false,
         "isWhitelistSupply":false,
         "usdExchange":2605.4,
         "isAcceptedAsCollateral":null,
         "isAcceptedAsLoan":null,
         "isAcceptedRepayment":null,
         "symbol":"MKR",
         "address":"0x5f0Da599BB2ccCfcf6Fdfd7D81743B6020864350"
      },
      {
         "id":11,
         "isWhitelistCollateral":false,
         "isWhitelistSupply":false,
         "usdExchange":0.548943,
         "isAcceptedAsCollateral":null,
         "isAcceptedAsLoan":null,
         "isAcceptedRepayment":null,
         "symbol":"BAT",
         "address":"0x101d82428437127bF1608F699CD651e6Abf9766E"
      },
      {
         "id":12,
         "isWhitelistCollateral":false,
         "isWhitelistSupply":false,
         "usdExchange":4.15,
         "isAcceptedAsCollateral":null,
         "isAcceptedAsLoan":null,
         "isAcceptedRepayment":null,
         "symbol":"EOS",
         "address":"0x56b6fB708fC5732DEC1Afc8D8556423A2EDcCbD6"
      },
      {
         "id":13,
         "isWhitelistCollateral":false,
         "isWhitelistSupply":false,
         "usdExchange":483.38,
         "isAcceptedAsCollateral":null,
         "isAcceptedAsLoan":null,
         "isAcceptedRepayment":null,
         "symbol":"BCH",
         "address":"0x8fF795a6F4D97E7887C79beA79aba5cc76444aDf"
      },
      {
         "id":14,
         "isWhitelistCollateral":false,
         "isWhitelistSupply":false,
         "usdExchange":17.74,
         "isAcceptedAsCollateral":null,
         "isAcceptedAsLoan":null,
         "isAcceptedRepayment":null,
         "symbol":"LINK",
         "address":"0xF8A0BF9cF54Bb92F17374d9e9A321E6a111a51bD"
      },
      {
         "id":15,
         "isWhitelistCollateral":true,
         "isWhitelistSupply":false,
         "usdExchange":1.31,
         "isAcceptedAsCollateral":null,
         "isAcceptedAsLoan":null,
         "isAcceptedRepayment":null,
         "symbol":"ADA",
         "address":"0xCE89CFcca3fedD566C7574902137eD31A4C9Ea40"
      },
      {
         "id":16,
         "isWhitelistCollateral":false,
         "isWhitelistSupply":false,
         "usdExchange":2.85,
         "isAcceptedAsCollateral":null,
         "isAcceptedAsLoan":null,
         "isAcceptedRepayment":null,
         "symbol":"XTZ",
         "address":"0x16939ef78684453bfDFb47825F8a5F714f12623a"
      },
      {
         "id":17,
         "isWhitelistCollateral":false,
         "isWhitelistSupply":false,
         "usdExchange":52.9,
         "isAcceptedAsCollateral":null,
         "isAcceptedAsLoan":null,
         "isAcceptedRepayment":null,
         "symbol":"FIL",
         "address":"0x0D8Ce2A99Bb6e3B7Db580eD848240e4a0F9aE153"
      },
      {
         "id":18,
         "isWhitelistCollateral":false,
         "isWhitelistSupply":false,
         "usdExchange":0.224898,
         "isAcceptedAsCollateral":null,
         "isAcceptedAsLoan":null,
         "isAcceptedRepayment":null,
         "symbol":"ELF",
         "address":"0xa3f020a5C92e15be13CAF0Ee5C95cF79585EeCC9"
      },
      {
         "id":19,
         "isWhitelistCollateral":false,
         "isWhitelistSupply":false,
         "usdExchange":0.02279509,
         "isAcceptedAsCollateral":null,
         "isAcceptedAsLoan":null,
         "isAcceptedRepayment":null,
         "symbol":"TCT",
         "address":"0xCA0a9Df6a8cAD800046C1DDc5755810718b65C44"
      },
      {
         "id":20,
         "isWhitelistCollateral":false,
         "isWhitelistSupply":false,
         "usdExchange":0.695583,
         "isAcceptedAsCollateral":null,
         "isAcceptedAsLoan":null,
         "isAcceptedRepayment":null,
         "symbol":"ONT",
         "address":"0xFd7B3A77848f1C2D67E05E54d78d174a0C850335"
      },
      {
         "id":21,
         "isWhitelistCollateral":false,
         "isWhitelistSupply":false,
         "usdExchange":11.97,
         "isAcceptedAsCollateral":null,
         "isAcceptedAsLoan":null,
         "isAcceptedRepayment":null,
         "symbol":"SNX",
         "address":"0x9Ac983826058b8a9C7Aa1C9171441191232E8404"
      },
      {
         "id":22,
         "isWhitelistCollateral":false,
         "isWhitelistSupply":false,
         "usdExchange":0.01887642,
         "isAcceptedAsCollateral":null,
         "isAcceptedAsLoan":null,
         "isAcceptedRepayment":null,
         "symbol":"IOTX",
         "address":"0x9678E42ceBEb63F23197D726B29b1CB20d0064E5"
      },
      {
         "id":23,
         "isWhitelistCollateral":false,
         "isWhitelistSupply":false,
         "usdExchange":1.0,
         "isAcceptedAsCollateral":null,
         "isAcceptedAsLoan":null,
         "isAcceptedRepayment":null,
         "symbol":"PAX",
         "address":"0xb7F8Cd00C5A06c0537E2aBfF0b58033d02e5E094"
      },
      {
         "id":24,
         "isWhitelistCollateral":false,
         "isWhitelistSupply":true,
         "usdExchange":1.0,
         "isAcceptedAsCollateral":null,
         "isAcceptedAsLoan":null,
         "isAcceptedRepayment":null,
         "symbol":"USDC",
         "address":"0xF02224B084f76fFd3427c8DD3055ea0dEA7F1EC2"
      },
      {
         "id":25,
         "isWhitelistCollateral":false,
         "isWhitelistSupply":false,
         "usdExchange":13.46,
         "isAcceptedAsCollateral":null,
         "isAcceptedAsLoan":null,
         "isAcceptedRepayment":null,
         "symbol":"ATOM",
         "address":"0x0Eb3a705fc54725037CC9e008bDede697f62F335"
      },
      {
         "id":26,
         "isWhitelistCollateral":false,
         "isWhitelistSupply":false,
         "usdExchange":1.9,
         "isAcceptedAsCollateral":null,
         "isAcceptedAsLoan":null,
         "isAcceptedRepayment":null,
         "symbol":"SXP",
         "address":"0x47BEAd2563dCBf3bF2c9407fEa4dC236fAbA485A"
      },
      {
         "id":27,
         "isWhitelistCollateral":false,
         "isWhitelistSupply":false,
         "usdExchange":6.72,
         "isAcceptedAsCollateral":null,
         "isAcceptedAsLoan":null,
         "isAcceptedRepayment":null,
         "symbol":"BAND",
         "address":"0xAD6cAEb32CD2c308980a548bD0Bc5AA4306c6c18"
      },
      {
         "id":28,
         "isWhitelistCollateral":false,
         "isWhitelistSupply":true,
         "usdExchange":1.01,
         "isAcceptedAsCollateral":null,
         "isAcceptedAsLoan":null,
         "isAcceptedRepayment":null,
         "symbol":"BUSD",
         "address":"0x544D0AD6BdDa001630941f6523D935E32cCAb604"
      },
      {
         "id":29,
         "isWhitelistCollateral":false,
         "isWhitelistSupply":true,
         "usdExchange":1.01,
         "isAcceptedAsCollateral":null,
         "isAcceptedAsLoan":null,
         "isAcceptedRepayment":null,
         "symbol":"DAI",
         "address":"0xaeeFfB36f4F8f0603AF63607f839D9457fc8b292"
      },
      {
         "id":30,
         "isWhitelistCollateral":false,
         "isWhitelistSupply":false,
         "usdExchange":409.92,
         "isAcceptedAsCollateral":null,
         "isAcceptedAsLoan":null,
         "isAcceptedRepayment":null,
         "symbol":"COMP",
         "address":"0x52CE071Bd9b1C4B00A0b92D298c512478CaD67e8"
      },
      {
         "id":31,
         "isWhitelistCollateral":false,
         "isWhitelistSupply":false,
         "usdExchange":32819,
         "isAcceptedAsCollateral":null,
         "isAcceptedAsLoan":null,
         "isAcceptedRepayment":null,
         "symbol":"YFI",
         "address":"0x88f1A5ae2A3BF98AEAF342D26B30a79438c9142e"
      },
      {
         "id":32,
         "isWhitelistCollateral":false,
         "isWhitelistSupply":false,
         "usdExchange":2126.95,
         "isAcceptedAsCollateral":null,
         "isAcceptedAsLoan":null,
         "isAcceptedRepayment":null,
         "symbol":"YFII",
         "address":"0x7F70642d88cf1C4a3a7abb072B53B929b653edA5"
      },
      {
         "id":33,
         "isWhitelistCollateral":false,
         "isWhitelistSupply":false,
         "usdExchange":2.09,
         "isAcceptedAsCollateral":null,
         "isAcceptedAsLoan":null,
         "isAcceptedRepayment":null,
         "symbol":"NEAR",
         "address":"0x1Fa4a73a3F0133f0025378af00236f3aBDEE5D63"
      },
      {
         "id":34,
         "isWhitelistCollateral":true,
         "isWhitelistSupply":false,
         "usdExchange":14.97,
         "isAcceptedAsCollateral":null,
         "isAcceptedAsLoan":null,
         "isAcceptedRepayment":null,
         "symbol":"DOT",
         "address":"0x62950ba1AdB2C867A24599a3666bf83Cf84c29Ed"
      },
      {
         "id":35,
         "isWhitelistCollateral":false,
         "isWhitelistSupply":false,
         "usdExchange":1.22,
         "isAcceptedAsCollateral":null,
         "isAcceptedAsLoan":null,
         "isAcceptedRepayment":null,
         "symbol":"BEL",
         "address":"0x8443f091997f06a61670B735ED92734F5628692F"
      },
      {
         "id":36,
         "isWhitelistCollateral":false,
         "isWhitelistSupply":false,
         "usdExchange":19.54,
         "isAcceptedAsCollateral":null,
         "isAcceptedAsLoan":null,
         "isAcceptedRepayment":null,
         "symbol":"UNI",
         "address":"0xBf5140A22578168FD562DCcF235E5D43A02ce9B1"
      },
      {
         "id":37,
         "isWhitelistCollateral":false,
         "isWhitelistSupply":false,
         "usdExchange":7.37,
         "isAcceptedAsCollateral":null,
         "isAcceptedAsLoan":null,
         "isAcceptedRepayment":null,
         "symbol":"INJ",
         "address":"0xa2B726B1145A4773F68593CF171187d8EBe4d495"
      },
      {
         "id":38,
         "isWhitelistCollateral":true,
         "isWhitelistSupply":false,
         "usdExchange":316.36,
         "isAcceptedAsCollateral":null,
         "isAcceptedAsLoan":null,
         "isAcceptedRepayment":null,
         "symbol":"BNB",
         "address":"0x0000000000000000000000000000000000000000"
      },
      {
         "id":4,
         "isWhitelistCollateral":true,
         "isWhitelistSupply":false,
         "usdExchange":null,
         "isAcceptedAsCollateral":null,
         "isAcceptedAsLoan":null,
         "isAcceptedRepayment":null,
         "symbol":"WBNB",
         "address":"0xae13d989daC2f0dEbFf460aC112a837C89BAa7cd"
      }
      ],
      collateralAcceptance: []
    }),
    methods: {
      remove (item) {
        const index = this.collateralAcceptance.indexOf(item.symbol)
        if (index >= 0) {
          this.collateralAcceptance.splice(index, 1)
        }
      }
    }
  }
</script>
